-- ==========================================================================
-- CyberOptRQ SQLite -> Supabase / PostgreSQL Seed Data Migration
-- Generated automatically with verified referential integrity & tenant isolation
-- ==========================================================================

BEGIN;

-- Table: organizations (2 rows)
INSERT INTO public."organizations" ("id", "name", "domain", "industry", "country_region", "technology_stack", "cloud_providers", "critical_assets", "business_assets", "security_controls", "existing_vulnerabilities", "financial_exposure", "created_at", "updated_at", "critical_services") VALUES ('org_abc_tech', 'ABC Technologies', 'abc.com', 'FinTech Cloud Banking', 'India / South Asia', '["Kubernetes", "Linux", "PostgreSQL", "AWS ECS", "Kafka"]', '["AWS", "Azure"]', '[{"id": "ASSET-001", "name": "Production Server", "criticality": 9.0, "exposure": "INTERNET_FACING"}]', '["Customer Database", "Proprietary Algorithm Repository"]', '["NIST-PR.AC-1", "CIS-4.1", "EDR", "WAF"]', '["CVE-2024-21626", "CVE-2023-46604"]', 4200000.0, '2026-09-17 01:36:44.623083', '2026-09-25 16:20:49.949542', '[]') ON CONFLICT DO NOTHING;
INSERT INTO public."organizations" ("id", "name", "domain", "industry", "country_region", "technology_stack", "cloud_providers", "critical_assets", "business_assets", "security_controls", "existing_vulnerabilities", "financial_exposure", "created_at", "updated_at", "critical_services") VALUES ('org_xyz_finance', 'XYZ Finance Corp', 'xyzfinance.com', 'Banking', 'India / South Asia', '[]', '[]', '[]', '[]', '[]', '[]', 3500000.0, '2026-09-25 16:55:26.331385', '2026-09-25 16:55:26.331385', '[]') ON CONFLICT DO NOTHING;

-- Table: users (4 rows)
INSERT INTO public."users" ("id", "username", "email", "hashed_password", "role", "organization", "is_active") VALUES (1, 'ciso_executive', 'ciso@cyberopt.internal', 'hashed_secret', 'CISO', 'Global Cyber Enterprise', 1) ON CONFLICT DO NOTHING;
INSERT INTO public."users" ("id", "username", "email", "hashed_password", "role", "organization", "is_active") VALUES (2, 'soc_analyst', 'soc@cyberopt.internal', 'hashed_secret', 'SOC', 'Global Cyber Enterprise', 1) ON CONFLICT DO NOTHING;
INSERT INTO public."users" ("id", "username", "email", "hashed_password", "role", "organization", "is_active") VALUES (3, 'security_lead', 'security@cyberopt.internal', 'hashed_secret', 'Security', 'Global Cyber Enterprise', 1) ON CONFLICT DO NOTHING;
INSERT INTO public."users" ("id", "username", "email", "hashed_password", "role", "organization", "is_active") VALUES (4, 'it_remediation', 'it@cyberopt.internal', 'hashed_secret', 'IT', 'Global Cyber Enterprise', 1) ON CONFLICT DO NOTHING;

-- Table: assets (8 rows)
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-001', 'Core Oracle Production DB', 'OT Asset', 9.5, 12000000.0, '10.0.1.50', 'Database Admin', 'INTERNAL', 12, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-002', 'Production K8s Microservices Cluster', 'Cloud Infrastructure', 9.0, 8500000.0, '10.0.2.100', 'DevOps Team', 'INTERNET_FACING', 6, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-003', 'Payment API Gateway', 'Cloud Infrastructure', 8.8, 6000000.0, '10.0.3.10', 'FinTech Engineering', 'INTERNET_FACING', 4, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-004', 'Executive Email & Active Directory', 'IT Asset', 8.2, 4500000.0, '10.0.1.12', 'IT Infrastructure', 'INTERNAL', 24, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-005', 'Customer Support Web Portal', 'IT Asset', 6.5, 2000000.0, '10.0.4.80', 'Customer Ops', 'INTERNET_FACING', 48, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-TEST-CONF', 'Air-Gapped Vault', 'OT Asset', 8.0, 5000000.0, NULL, NULL, 'ISOLATED', 24, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-TEST-SPARSE', 'Generic Server', 'IT Asset', 5.0, 1000000.0, NULL, NULL, 'INTERNAL', 24, 'org_abc_tech') ON CONFLICT DO NOTHING;
INSERT INTO public."assets" ("id", "name", "asset_type", "criticality_score", "financial_value", "ip_address", "owner", "exposure_level", "sla_hours", "organization_id") VALUES ('ASSET-XYZ-001', 'Core Banking Transaction Server', 'Cloud Infrastructure', 9.8, 8500000.0, NULL, NULL, 'INTERNAL', 24, 'org_xyz_finance') ON CONFLICT DO NOTHING;

-- Table: vulnerabilities (7 rows)
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-2024-21626', 'CVE-2024-21626', 'runc Container Escape RCE', 9.8, 0.88, 1, 'T1190', 'Exploit Public-Facing Application', 'CWE-787', 'Linux Container Runtime / runc', 'NETWORK', 'LOW', 'NONE', 3500000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-2024-3094', 'CVE-2024-3094', 'XZ Utils Supply Chain Backdoor', 10.0, 0.95, 1, 'T1068', 'Exploitation for Privilege Escalation', 'CWE-94', 'liblzma / SSH Daemon', 'NETWORK', 'LOW', 'NONE', 5000000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-2023-4863', 'CVE-2023-4863', 'libwebp Heap Buffer Overflow', 8.8, 0.72, 1, 'T1210', 'Exploitation of Remote Services', 'CWE-787', 'WebP Image Decoder', 'NETWORK', 'LOW', 'NONE', 1800000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-2023-23397', 'CVE-2023-23397', 'Microsoft Outlook NTLM Hash Elevation', 9.8, 0.91, 1, 'T1078', 'Valid Accounts', 'CWE-200', 'Microsoft Outlook', 'NETWORK', 'LOW', 'NONE', 2200000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-2023-38831', 'CVE-2023-38831', 'WinRAR Arbitrary Code Execution', 7.8, 0.64, 0, 'T1059', 'Command & Scripting Interpreter', 'CWE-78', 'WinRAR Shell Extension', 'LOCAL', 'LOW', 'NONE', 950000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-TEST-CONF', 'CVE-TEST-CONF', 'Theoretical Parsing Flaw', 9.8, 0.01, 0, 'T1059', 'Exploit Public-Facing Application', 'CWE-787', 'Linux Container Runtime / runc', 'NETWORK', 'LOW', 'NONE', 1500000.0) ON CONFLICT DO NOTHING;
INSERT INTO public."vulnerabilities" ("id", "cve_id", "title", "cvss_score", "epss_score", "cisa_kev", "mitre_attack_technique", "mitre_attack_name", "cwe_id", "affected_products", "attack_vector", "complexity", "privileges_required", "financial_impact_base") VALUES ('CVE-TEST-SPARSE', 'CVE-TEST-SPARSE', 'Unclassified Bug', 6.0, 0.1, 0, NULL, NULL, NULL, NULL, 'NETWORK', 'LOW', 'NONE', 500000.0) ON CONFLICT DO NOTHING;

-- Table: security_controls (5 rows)
INSERT INTO public."security_controls" ("id", "code", "name", "category", "cost", "effectiveness", "implementation_time_days", "status", "requires_control_id") VALUES ('CTRL-001', 'ZERO_TRUST', 'Zero-Trust Microsegmentation & Network Isolation', 'Firewall', 300000.0, 0.85, 5, 'PROPOSED', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."security_controls" ("id", "code", "name", "category", "cost", "effectiveness", "implementation_time_days", "status", "requires_control_id") VALUES ('CTRL-002', 'EDR_PATCH', 'Automated EDR & Container Guard Patching', 'EDR', 200000.0, 0.9, 3, 'PROPOSED', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."security_controls" ("id", "code", "name", "category", "cost", "effectiveness", "implementation_time_days", "status", "requires_control_id") VALUES ('CTRL-003', 'WAF_BOT', 'Cloud Next-Gen WAF & Bot Mitigation', 'WAF', 250000.0, 0.75, 4, 'PROPOSED', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."security_controls" ("id", "code", "name", "category", "cost", "effectiveness", "implementation_time_days", "status", "requires_control_id") VALUES ('CTRL-004', 'IAM_MFA', 'FIDO2 Hardware Key MFA Enforcement', 'IAM', 100000.0, 0.95, 2, 'PROPOSED', NULL) ON CONFLICT DO NOTHING;
INSERT INTO public."security_controls" ("id", "code", "name", "category", "cost", "effectiveness", "implementation_time_days", "status", "requires_control_id") VALUES ('CTRL-005', 'SIEM_SOAR', 'SIEM + SOAR Automated Incident Response', 'SIEM', 150000.0, 0.8, 7, 'PROPOSED', 'CTRL-002') ON CONFLICT DO NOTHING;

-- Table: incident_history (3 rows)
INSERT INTO public."incident_history" ("id", "asset_id", "incident_name", "incident_type", "loss_incurred", "date_occurred", "severity", "description", "loss_inr") VALUES (1, 'ASSET-001', 'Attempted SQL Injection & Data Probe', 'Data Probe', 150000.0, '2025-11-14', 'HIGH', NULL, 0.0) ON CONFLICT DO NOTHING;
INSERT INTO public."incident_history" ("id", "asset_id", "incident_name", "incident_type", "loss_incurred", "date_occurred", "severity", "description", "loss_inr") VALUES (2, 'ASSET-002', 'Cryptomining Container Intrusion', 'Ransomware / Exploit', 450000.0, '2026-02-01', 'HIGH', NULL, 0.0) ON CONFLICT DO NOTHING;
INSERT INTO public."incident_history" ("id", "asset_id", "incident_name", "incident_type", "loss_incurred", "date_occurred", "severity", "description", "loss_inr") VALUES (3, 'ASSET-003', 'Volumetric DDoS Spike on Payment Gateway', 'DDoS', 300000.0, '2026-05-18', 'HIGH', NULL, 0.0) ON CONFLICT DO NOTHING;

COMMIT;