'use strict';

/**
 * cyber_risk_audit.js
 * Hyperledger Fabric Smart Contract / Chaincode
 * SIH 2026 Problem Statement 26105:
 * AI-Powered Continuous Cyber Risk Quantification & Investment Optimization Platform
 *
 * Implements immutable on-chain audit records for:
 * 1. Risk Assessments (P1-P4 -> Meta Model -> Org-Specific Model -> EAL)
 * 2. Investment Decisions (Knapsack Portfolio Optimization)
 * 3. Remediation Actions (Patch / Mitigation Deployed)
 * 4. Reassessments (Post-Mitigation Residual Risk Reduction)
 */

const { Contract } = require('fabric-contract-api');

class CyberRiskAuditContract extends Contract {

    constructor() {
        super('CyberRiskAuditContract');
    }

    /**
     * Initializes ledger with genesis metadata
     */
    async initLedger(ctx) {
        console.info('=== Initializing Cyber Risk Audit Ledger ===');
        const genesisRecord = {
            doc_type: 'genesis_metadata',
            channel: 'cyber-risk-channel',
            consensus_protocol: 'etcdraft (Raft CFT Ordering)',
            hashing_algorithm: 'SHA-256 State Tree',
            initialized_at: new Date().toISOString(),
            status: 'ACTIVE_PERMISSIONED_LEDGER'
        };
        await ctx.stub.putState('GENESIS_INFO', Buffer.from(JSON.stringify(genesisRecord)));
        console.info('=== Cyber Risk Audit Ledger Initialized Successfully ===');
    }

    /**
     * A. Record an AI-quantified Risk Assessment
     */
    async recordRiskAssessment(ctx, eventId, orgId, threatId, metaRisk, orgRisk, eal, detailsJson) {
        if (!eventId || !orgId) {
            throw new Error('Missing required fields: eventId and orgId are mandatory.');
        }

        const txTimestamp = new Date(ctx.stub.getTxTimestamp().seconds.low * 1000).toISOString();
        const clientIdentity = ctx.clientIdentity.getMSPID();

        const auditEvent = {
            doc_type: 'audit_event',
            event_id: eventId,
            event_type: 'RISK_ASSESSMENT',
            organization_id: orgId,
            threat_id: threatId || 'N/A',
            meta_risk: parseFloat(metaRisk) || 0.0,
            organization_risk: parseFloat(orgRisk) || 0.0,
            expected_annual_loss_inr: parseFloat(eal) || 0.0,
            details: detailsJson ? JSON.parse(detailsJson) : {},
            recorded_by_msp: clientIdentity,
            tx_id: ctx.stub.getTxID(),
            timestamp: txTimestamp
        };

        // Primary key lookup
        await ctx.stub.putState(`EVENT_${eventId}`, Buffer.from(JSON.stringify(auditEvent)));

        // Composite key for organization timeline
        const orgHistoryKey = ctx.stub.createCompositeKey('Org~Event', [orgId, txTimestamp, eventId]);
        await ctx.stub.putState(orgHistoryKey, Buffer.from(JSON.stringify(auditEvent)));

        // Update latest risk pointer for fast querying
        await ctx.stub.putState(`LATEST_RISK_${orgId}`, Buffer.from(JSON.stringify({
            organization_id: orgId,
            latest_risk: parseFloat(orgRisk),
            latest_eal_inr: parseFloat(eal),
            last_event_id: eventId,
            last_updated: txTimestamp
        })));

        return JSON.stringify(auditEvent);
    }

    /**
     * B. Record an Investment Decision generated by Knapsack Optimizer
     */
    async recordInvestmentDecision(ctx, eventId, orgId, controlId, investmentCost, expectedReduction, rosi, detailsJson) {
        if (!eventId || !orgId || !controlId) {
            throw new Error('Missing required fields: eventId, orgId, and controlId are mandatory.');
        }

        const txTimestamp = new Date(ctx.stub.getTxTimestamp().seconds.low * 1000).toISOString();
        const clientIdentity = ctx.clientIdentity.getMSPID();

        const auditEvent = {
            doc_type: 'audit_event',
            event_id: eventId,
            event_type: 'INVESTMENT_DECISION',
            organization_id: orgId,
            recommended_control_id: controlId,
            investment_cost_inr: parseFloat(investmentCost) || 0.0,
            expected_risk_reduction_pts: parseFloat(expectedReduction) || 0.0,
            expected_rosi_pct: parseFloat(rosi) || 0.0,
            details: detailsJson ? JSON.parse(detailsJson) : {},
            recorded_by_msp: clientIdentity,
            tx_id: ctx.stub.getTxID(),
            timestamp: txTimestamp
        };

        await ctx.stub.putState(`EVENT_${eventId}`, Buffer.from(JSON.stringify(auditEvent)));
        const orgHistoryKey = ctx.stub.createCompositeKey('Org~Event', [orgId, txTimestamp, eventId]);
        await ctx.stub.putState(orgHistoryKey, Buffer.from(JSON.stringify(auditEvent)));

        return JSON.stringify(auditEvent);
    }

    /**
     * C. Record a verified Security Remediation action
     */
    async recordRemediation(ctx, eventId, orgId, assetId, actionTaken, verifiedBy, detailsJson) {
        if (!eventId || !orgId || !assetId) {
            throw new Error('Missing required fields: eventId, orgId, and assetId are mandatory.');
        }

        const txTimestamp = new Date(ctx.stub.getTxTimestamp().seconds.low * 1000).toISOString();
        const clientIdentity = ctx.clientIdentity.getMSPID();

        const auditEvent = {
            doc_type: 'audit_event',
            event_id: eventId,
            event_type: 'REMEDIATION',
            organization_id: orgId,
            asset_id: assetId,
            action_taken: actionTaken || 'SECURITY_REMEDIATION_APPLIED',
            verified_by_user: verifiedBy || 'AUTHORIZED_SYSTEM',
            details: detailsJson ? JSON.parse(detailsJson) : {},
            recorded_by_msp: clientIdentity,
            tx_id: ctx.stub.getTxID(),
            timestamp: txTimestamp
        };

        await ctx.stub.putState(`EVENT_${eventId}`, Buffer.from(JSON.stringify(auditEvent)));
        const orgHistoryKey = ctx.stub.createCompositeKey('Org~Event', [orgId, txTimestamp, eventId]);
        await ctx.stub.putState(orgHistoryKey, Buffer.from(JSON.stringify(auditEvent)));

        const assetHistoryKey = ctx.stub.createCompositeKey('Asset~Event', [assetId, txTimestamp, eventId]);
        await ctx.stub.putState(assetHistoryKey, Buffer.from(JSON.stringify(auditEvent)));

        return JSON.stringify(auditEvent);
    }

    /**
     * D. Record a post-remediation Risk Reassessment
     */
    async recordReassessment(ctx, eventId, orgId, previousRisk, newRisk, residualEal, detailsJson) {
        if (!eventId || !orgId) {
            throw new Error('Missing required fields: eventId and orgId are mandatory.');
        }

        const txTimestamp = new Date(ctx.stub.getTxTimestamp().seconds.low * 1000).toISOString();
        const clientIdentity = ctx.clientIdentity.getMSPID();

        const auditEvent = {
            doc_type: 'audit_event',
            event_id: eventId,
            event_type: 'REASSESSMENT',
            organization_id: orgId,
            previous_risk: parseFloat(previousRisk) || 0.0,
            new_risk: parseFloat(newRisk) || 0.0,
            residual_eal_inr: parseFloat(residualEal) || 0.0,
            risk_reduction_achieved: (parseFloat(previousRisk) || 0.0) - (parseFloat(newRisk) || 0.0),
            details: detailsJson ? JSON.parse(detailsJson) : {},
            recorded_by_msp: clientIdentity,
            tx_id: ctx.stub.getTxID(),
            timestamp: txTimestamp
        };

        await ctx.stub.putState(`EVENT_${eventId}`, Buffer.from(JSON.stringify(auditEvent)));
        const orgHistoryKey = ctx.stub.createCompositeKey('Org~Event', [orgId, txTimestamp, eventId]);
        await ctx.stub.putState(orgHistoryKey, Buffer.from(JSON.stringify(auditEvent)));

        // Update latest risk pointer
        await ctx.stub.putState(`LATEST_RISK_${orgId}`, Buffer.from(JSON.stringify({
            organization_id: orgId,
            latest_risk: parseFloat(newRisk),
            latest_eal_inr: parseFloat(residualEal),
            last_event_id: eventId,
            last_updated: txTimestamp
        })));

        return JSON.stringify(auditEvent);
    }

    /**
     * E. Query single audit event by ID
     */
    async getAuditEvent(ctx, eventId) {
        const dataBytes = await ctx.stub.getState(`EVENT_${eventId}`);
        if (!dataBytes || dataBytes.length === 0) {
            throw new Error(`Audit event with ID ${eventId} does not exist on Fabric ledger.`);
        }
        return dataBytes.toString();
    }

    /**
     * F. Query full timeline of events for an Organization
     */
    async getOrganizationHistory(ctx, orgId) {
        const iterator = await ctx.stub.getStateByPartialCompositeKey('Org~Event', [orgId]);
        const results = [];
        let item = await iterator.next();
        while (!item.done) {
            if (item.value && item.value.value.toString()) {
                results.push(JSON.parse(item.value.value.toString('utf8')));
            }
            item = await iterator.next();
        }
        await iterator.close();
        return JSON.stringify(results);
    }

    /**
     * G. Query remediation history for an Asset
     */
    async getAssetHistory(ctx, assetId) {
        const iterator = await ctx.stub.getStateByPartialCompositeKey('Asset~Event', [assetId]);
        const results = [];
        let item = await iterator.next();
        while (!item.done) {
            if (item.value && item.value.value.toString()) {
                results.push(JSON.parse(item.value.value.toString('utf8')));
            }
            item = await iterator.next();
        }
        await iterator.close();
        return JSON.stringify(results);
    }

    /**
     * H. Query latest risk posture and EAL for an Organization
     */
    async getLatestRisk(ctx, orgId) {
        const dataBytes = await ctx.stub.getState(`LATEST_RISK_${orgId}`);
        if (!dataBytes || dataBytes.length === 0) {
            throw new Error(`No risk posture assessments found for organization ${orgId}.`);
        }
        return dataBytes.toString();
    }

    // Method Aliases for Contract Compatibility
    async CreateRiskAssessment(ctx, eventId, orgId, threatId, metaRisk, orgRisk, eal, detailsJson) {
        return this.recordRiskAssessment(ctx, eventId, orgId, threatId, metaRisk, orgRisk, eal, detailsJson);
    }

    async GetRiskAssessment(ctx, eventId) {
        return this.getAuditEvent(ctx, eventId);
    }

    async CreateInvestmentDecision(ctx, eventId, orgId, controlId, investmentCost, expectedReduction, rosi, detailsJson) {
        return this.recordInvestmentDecision(ctx, eventId, orgId, controlId, investmentCost, expectedReduction, rosi, detailsJson);
    }

    async CreateRemediation(ctx, eventId, orgId, assetId, actionTaken, verifiedBy, detailsJson) {
        return this.recordRemediation(ctx, eventId, orgId, assetId, actionTaken, verifiedBy, detailsJson);
    }

    async CreateReassessment(ctx, eventId, orgId, previousRisk, newRisk, residualEal, detailsJson) {
        return this.recordReassessment(ctx, eventId, orgId, previousRisk, newRisk, residualEal, detailsJson);
    }

    async GetAuditHistory(ctx, orgId) {
        return this.getOrganizationHistory(ctx, orgId);
    }
}

module.exports = CyberRiskAuditContract;
